Source Code/armydb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import  include, url

 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("armydbapp.urls")),
]

Source Code/armydbapp/urls.py
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'armydbapp'

urlpatterns = [
    path('home', views.home, name='home'),
    path('login', views.login_view, name='login'),
    path('loguser', views.login_user, name='loguser'),
    path('logout', views.logout_user, name='logout'),
    path('', views.index, name='index'),
    path('soldier_list', views.soldier_list, name='soldier_list'),
    path('soldier_search', views.soldier_search, name='soldier_search'),
    path('add_soldier', views.add_soldier, name='add_soldier'),
    path('submit_soldier', views.submit_soldier, name='submit_soldier'),
    path('add_reward', views.add_reward, name='add_reward'),
    path('submit_reward', views.submit_reward, name='submit_reward'),
    path('add_vacation', views.add_vacation, name='add_vacation'),
    path('submit_vacation', views.submit_vacation, name='submit_vacation'),
    path('add_vacation_sick', views.add_vacation_sick, name='add_vacation_sick'),
    path('submit_vacation_sick', views.submit_vacation_sick, name='submit_vacation_sick'),
    path('add_punishment', views.add_punishment, name='add_punishment'),
    path('submit_punishment', views.submit_punishment, name='submit_punishment'),          
    path('soldier_information', views.soldier_information, name='soldier_information'),
    path('delete_soldier', views.delete_soldier, name='delete_soldier'),
    path('submit_delete_soldier', views.submit_delete_soldier, name='submit_delete_soldier'),
    path('dont_delete_soldier', views.dont_delete_soldier, name='dont_delete_soldier'),
    path('awaiting_trial', views.awaiting_trial, name='awaiting_trial'),
    path('submit_awaiting_trial', views.submit_awaiting_trial, name='submit_awaiting_trial'),
    path('dont_awaiting_trial', views.dont_awaiting_trial, name='dont_awaiting_trial'),
    path('trial_done', views.trial_done, name='trial_done'),
    path('submit_trial_done', views.submit_trial_done, name='submit_trial_done'),
    path('dont_trial_done', views.dont_trial_done, name='dont_trial_done'),
    path('reward_consumed', views.reward_consumed, name='reward_consumed'),
    path('submit_reward_consumed', views.submit_reward_consumed, name='submit_reward_consumed'),
    path('dont_reward_consumed', views.dont_reward_consumed, name='dont_reward_consumed'),
    path('absent', views.absent, name='absent'),
    path('submit_absent', views.submit_absent, name='submit_absent'),
    path('dont_absent', views.dont_absent, name='dont_absent'),
    path('present', views.present, name='present'),
    path('submit_present', views.submit_present, name='submit_present'),
    path('dont_present', views.dont_present, name='dont_present'),
    path('outing', views.outing, name='outing'),
    path('submit_outing', views.submit_outing, name='submit_outing'),
    path('no_outing', views.no_outing, name='no_outing'),
    path('submit_no_outing', views.submit_no_outing, name='submit_no_outing'),
    path('dont_no_outing', views.dont_no_outing, name='dont_no_outing'),
    path('mission', views.mission, name='mission'),
    path('submit_mission', views.submit_mission, name='submit_mission'),
    path('no_mission', views.no_mission, name='no_mission'),
    path('submit_no_mission', views.submit_no_mission, name='submit_no_mission'),
    path('dont_no_mission', views.dont_no_mission, name='dont_no_mission'),
    path('change_army_unit', views.change_army_unit, name='change_army_unit'),
    path('submit_change_army_unit', views.submit_change_army_unit, name='submit_change_army_unit'),
    path('dont_change_army_unit', views.dont_change_army_unit, name='dont_change_army_unit'),
    path('reward_list', views.reward_list, name='reward_list'),
    path('punished_list', views.punished_list, name='punished_list'),
    path('late_vacation_list', views.late_vacation_list, name='late_vacation_list'),
    path('return_today_list', views.return_today_list, name='return_today_list'),
    path('late_unit_list', views.late_unit_list, name='late_unit_list'),
    path('vacation_choice', views.vacation_choice, name='vacation_choice'),
    path('katiba_headquart', views.katiba_headquart, name='katiba_headquart'),
    path('s1_headquart', views.s1_headquart, name='s1_headquart'),

    path('قياس1', views._قياس1, name='قياس1'),
    path('13احمد', views._13احمد, name='13احمد'),
    path('11رياض', views._11رياض, name='11رياض'),
    path('11محمود', views._11محمود, name='11محمود'),
    path('12رياض', views._12رياض, name='12رياض'),
    path('12محمود', views._12محمود, name='12محمود'),
    path('13رياض', views._13رياض, name='13رياض'),
    path('13محمود', views._13محمود, name='13محمود'),
    path('14رياض', views._14رياض, name='14رياض'),
    path('14محمود', views._14محمود, name='14محمود'),
    path('15رياض', views._15رياض, name='15رياض'),
    path('15محمود', views._15محمود, name='15محمود'),
    path('1سعيد', views._1سعيد, name='1سعيد'),
    path('1عرب', views._1عرب, name='1عرب'),
    path('2سعيد', views._2سعيد, name='2سعيد'),
    path('2عرب', views._2عرب, name='2عرب'),

    path('قياس2', views._قياس2, name='قياس2'),
    path('3عرب', views._3عرب, name='3عرب'),
    path('4سعيد', views._4سعيد, name='4سعيد'),
    path('4عرب', views._4عرب, name='4عرب'),
    path('5عرب', views._5عرب, name='5عرب'),
    path('6عرب', views._6عرب, name='6عرب'),
    path('7عرب', views._7عرب, name='7عرب'),
    path('8عرب', views._8عرب, name='8عرب'),
    path('9سعيد', views._9سعيد, name='9سعيد'),
    path('9عرب', views._9عرب, name='9عرب'),
    path('9عرب', views._9عرب, name='9عرب'),

    path('قياس3', views._قياس3, name='قياس3'),
    path('11عرب', views._11عرب, name='11عرب'),
    path('12سعيد', views._12سعيد, name='12سعيد'),
    path('13سعيد', views._13سعيد, name='13سعيد'),
    path('13عرب', views._13عرب, name='13عرب'),


    path('dof3a_radif', views.dof3a_radif, name='dof3a_radif'),
    path('awaiting_trial_list', views.awaiting_trial_list, name='awaiting_trial_list'),
    path('absent_list', views.absent_list, name='absent_list'),
    path('add_img', views.add_img, name='add_img'),
    path('submit_add_img', views.submit_add_img, name='submit_add_img'),
    path('add_promotion', views.add_promotion, name='add_promotion'),
    path('submit_promotion', views.submit_promotion, name='submit_promotion'),
    path('add_zucchini', views.add_zucchini, name='add_zucchini'),
    path('submit_zucchini', views.submit_zucchini, name='submit_zucchini'),
    path('add_work_assigned', views.add_work_assigned, name='add_work_assigned'),
    path('submit_work_assigned', views.submit_work_assigned, name='submit_work_assigned'),
    path('add_job', views.add_job, name='add_job'),
    path('submit_job', views.submit_job, name='submit_job'),
    path('s1_all', views.s1_all, name='s1_all'),
    path('s2_all', views.s2_all, name='s2_all'),
    path('s3_all', views.s3_all, name='s3_all'),
    path('add_remark', views.add_remark, name='add_remark'),
    path('submit_remark', views.submit_remark, name='submit_remark'),
    path('mawkaf_a5eir_sarfaya', views.mawkaf_a5eir_sarfaya, name='mawkaf_a5eir_sarfaya'),
    path('submit_mawkaf_a5eir_sarfaya', views.submit_mawkaf_a5eir_sarfaya, name='submit_mawkaf_a5eir_sarfaya'),
    path('present_list', views.present_list, name='present_list'),
    path('absent_indexList', views.absent_indexList, name='absent_indexList'),
    path('out_list', views.out_list, name='out_list'),
    path('vacation_list', views.vacation_list, name='vacation_list'),
    path('vacation_sick_list', views.vacation_sick_list, name='vacation_sick_list'),
    path('mission_list', views.mission_list, name='mission_list'),
    path('prison_list', views.prison_list, name='prison_list'),
    #officer_views
    path('add_officer', views.add_officer, name='add_officer'),
    path('submit_officer', views.submit_officer, name='submit_officer'),
    path('add_img_officer', views.add_img_officer, name='add_img_officer'),
    path('submit_add_img_officer', views.submit_add_img_officer, name='submit_add_img_officer'),
    path('add_reward_officer', views.add_reward_officer, name='add_reward_officer'),
    path('submit_reward_officer', views.submit_reward_officer, name='submit_reward_officer'),
    path('add_work_assigned_officer', views.add_work_assigned_officer, name='add_work_assigned_officer'),
    path('submit_work_assigned_officer', views.submit_work_assigned_officer, name='submit_work_assigned_officer'),
    path('add_remark_officer', views.add_remark_officer, name='add_remark_officer'),
    path('submit_remark_officer', views.submit_remark_officer, name='submit_remark_officer'),
    path('add_vacation_officer', views.add_vacation_officer, name='add_vacation_officer'),
    path('submit_vacation_officer', views.submit_vacation_officer, name='submit_vacation_officer'),
    path('add_vacation_sick_officer', views.add_vacation_sick_officer, name='add_vacation_sick_officer'),
    path('submit_vacation_sick_officer', views.submit_vacation_sick_officer, name='submit_vacation_sick_officer'),
    path('add_punishment_officer', views.add_punishment_officer, name='add_punishment_officer'),
    path('submit_punishment_officer', views.submit_punishment_officer, name='submit_punishment_officer'),
    path('officer_information', views.officer_information, name='officer_information'),
    path('delete_officer', views.delete_officer, name='delete_officer'),
    path('submit_delete_officer', views.submit_delete_officer, name='submit_delete_officer'),
    path('dont_delete_officer', views.dont_delete_officer, name='dont_delete_officer'),
    path('add_promotion_officer', views.add_promotion_officer, name='add_promotion_officer'),
    path('submit_promotion_officer', views.submit_promotion_officer, name='submit_promotion_officer'),

Source Code/armydbapp/templates/armydbapp/add_promotion_officer.html
{% extends "armydbapp/soldier_admin_base.html" %}
{% block content %}
<form action="{% url 'armydbapp:submit_promotion_officer' %}" method="post">
{% csrf_token %}
<div>
    <div class="h1 mb-5" style="position: relative; left: 80%;">إضافة ترقي</div>
    
    <div class="input-group mb-3">
        <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3" name="officer_number" value={{officer_id}} hidden>
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text" for="inputGroupSelect01"> الترقي الي رتبة</label>
        </div>

        <select class="custom-select" id="inputGroupSelect01" name="rank" required>
          <option value="ملازم">ملازم</option>
          <option value="ملازم اول">ملازم اول</option>
          <option value="نقيب">نقيب</option>
          <option value="رائد">رائد</option>
          <option value="مقدم">مقدم</option>
          <option value="عقيد">عقيد</option>
        </select>
    </div>


    <button class="btn btn-success" type="submit" style="width:100%;">موافق</button>
</div>
</form>
{% endblock content %}

Source Code/armydbapp/templates/armydbapp/add_remarks.html
{% extends "armydbapp/soldier_admin_base.html" %}
{% block content %}
<form action="{% url 'armydbapp:submit_remark' %}" method="post">
{% csrf_token %}
<div>
    <div class="h1 mb-5" style="position: relative; left: 80%;" dir="rtl">إضافة نقطة</div> 
    <div class="input-group mb-3">
        <div class="input-group-prepend"><span class="input-group-text" id="basic-addon3">النقطة</span></div>
        <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3" name="soldier_number" value={{soldier_id}} hidden>
        <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3" name="remarks"   required>
    </div>
    <button class="btn btn-success" type="submit" style="width:100%;">موافق</button>
</div>
</form>
{% endblock content %}

Source Code/armydbapp/templates/armydbapp/add_reward.html
{% extends "armydbapp/soldier_admin_base.html" %}
{% block content %}
<form action="{% url 'armydbapp:submit_reward' %}" method="post">
{% csrf_token %}
<div>
    <div class="h1 mb-5" style="position: relative; left: 80%;" dir="rtl">إضافة منحة</div> 
    <div class="input-group mb-3">
        <div class="input-group-prepend"><span class="input-group-text" id="basic-addon3">عدد ايام المنحة</span></div>
        <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3" name="soldier_number" value={{soldier_id}} hidden>
        <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3" name="days_rewarded" required>
    </div>
    <button class="btn btn-success" type="submit" style="width:100%;">موافق</button>
</div>
</form>
{% endblock content %}

Source Code/armydbapp/templates/armydbapp/present.html
{% extends "armydbapp/soldier_admin_base.html" %}
{% block content %}
<form action="{% url 'armydbapp:submit_present' %}" method="post">
{% csrf_token %}
<div>
    <div class="h1 mb-5" style="position: relative; left: 80%;" dir="rtl">حضـــور</div> 
    <div class="input-group mb-3">
        <h1>هل توافق أن الجندي حضور؟</h1>
        <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3" name="soldier_number" value="{{soldier_number}}">
    </div>
    <button class="btn btn-success" type="submit" style="width:50%; margin:10px;position: relative; left: 25%;">نعم</button>
   
</div>
</form>
<form action="{% url 'armydbapp:dont_present' %}" method="post">
{% csrf_token %}
        <button class="btn btn-success" type="submit" style="width:50%; margin:10px;position: relative; left: 25%;">لا</button>
</form>
{% endblock content %}

Source Code/armydbapp/templates/armydbapp/soldier_list_filter.html
{% extends "armydbapp/soldier_admin_base.html" %}
{% block content %}
{% load static %}
<style>
  * { box-sizing: border-box; }
  body {
    font: 16px Arial; 
  }
  .autocomplete {
    /*the container must be positioned relative:*/
    position: relative;
    display: inline-block;
  }
  input {
    border: 1px solid transparent;
    background-color: #f1f1f1;
    padding: 10px;
    font-size: 16px;
  }
  input[type=text] {
    background-color: #f1f1f1;
    width: 100%;
  }
  input[type=submit] {
    background-color: DodgerBlue;
    color: #fff;
  }
  .autocomplete-items {
    position: absolute;
    border: 1px solid #d4d4d4;
    border-bottom: none;
    border-top: none;
    z-index: 99;
    /*position the autocomplete items to be the same width as the container:*/
    top: 100%;
    left: 0;
    right: 0;
  }
  .autocomplete-items div {
    padding: 10px;
    cursor: pointer;
    background-color: #fff; 
    border-bottom: 1px solid #d4d4d4; 
  }
  .autocomplete-items div:hover {
    /*when hovering an item:*/
    background-color: #e9e9e9; 
  }
  .autocomplete-active {
    /*when navigating through the items using the arrow keys:*/
    background-color: DodgerBlue !important; 
    color: #ffffff; 
  }
  
  
  
  
   table tr th {
      font-size: 14px;
      background-color:#00d1b2;
    }
    table tr td {
      border:1px;
      border-style: solid;
      font-size: 12px;
      text-align: center;
    }
    
    
  
    
    li {
        float: right;
    }
    
    li a, .dropbtn {
        display: inline-block;
        color: black;
        text-align: center;
        
        text-decoration: none;
    }
    
    li a:hover, .dropdown:hover .dropbtn {
        background-color: rgb(4, 0, 255);
    }
    
    li.dropdown {
        display: inline-block;
    }
    
    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }
    
    .dropdown-content a {
        color: black;
        padding: 12px 10px;
        text-decoration: none;
        display: block;
        text-align: right;
    }
    
    .dropdown-content a:hover {background-color: #f1f1f1;}
    
    .dropdown:hover .dropdown-content {
        display: block;
    }
    .dropbtn {
        width: 160px;}
  
    
  
    .dropdown-menu{
      text-align: center;
    }

    .pagination {
    text-align: center;
    margin-top: 1em;
    justify-content: center !important;
}

.pagination-number {
    padding: 0.5em 0.8em;
    border-radius: 2px;
    color: #fff;
    background-color: #6D85C7;
}

.pagination-number:hover, .pagination-current {
    background-color: #3354AA;      
}

.pagination-action {
    margin: 0 0.1em;
    display: inline-block;
    padding: 0.5em 0.5em;
    color: black !important;
    background-color: #3354AA; 
    font-size: 1.3em;
}
.pagination-number:hover { color: #fff}

.pagination-action:hover, .pagination-previous, .pagination-next {
    color: #3354AA;  
}
    </style>
 <!--
 <div class="pagination mb-4">

    {% if soldier_list_filtered.has_previous %}
      <a class="pagination-action arabic" href="?page=1">
       <i class="fa fa-angle-double-right" aria-hidden="true"></i>
      </a>
      <a class="pagination-action arabic" href="?page={{ soldier_list_filtered.previous_page_number }}">
        <i class="fa fa-angle-right" aria-hidden="true"></i>
      </a>
    {% endif %}
  
    {% for num in soldier_list_filtered.paginator.page_range %}
  
      {% if soldier_list_filtered.number == num %}
      <span class="pagination-number pagination-current arabic mx-1">{{ num }}</span>
      {% elif num > soldier_list_filtered.number|add:'-3' and num < soldier_list_filtered.number|add:'3' %}
      <a class="pagination-number arabic mx-1" href="?page={{ num }}">{{ num }}</a>
      {% endif %}
  
    {% endfor %}
  
    {% if soldier_list_filtered.has_next %}
      <a class="pagination-action arabic" href="?page={{ soldier_list_filtered.next_page_number }}">
        <i class="fa fa-angle-left" aria-hidden="true"></i>
      </a>
      <a class="pagination-action arabic" href="?page={{ soldier_list_filtered.paginator.num_pages }}">
        <i class="fa fa-angle-double-left" aria-hidden="true"></i>
      </a>
    {% endif %}
  
  </div> -->
<div class="table-responsive">
 <table class="table table-bordered  table-hover " style="text-align:center;" dir="rtl">
  <thead >
    <tr>
      <th scope="col" style="text-align: center;">م</th>
      <th class="arabic border" scope="col" style="text-align:center;">الاسم</th>
      <th class="arabic border" scope="col" style="text-align: center;">الرقم العسكري</th>
      <th class="arabic border" scope="col" style="text-align: center;">التمركز</th>
      <th class="arabic border" scope="col" style="text-align: center;">النقطة</th>
      <th class="arabic border" scope="col" style="text-align: center;" >تاريخ التجنيد</th>
      <th class="arabic border" scope="col" style="text-align: center;" >تاريخ التسريح</th>
      <th class="arabic border" scope="col" style="text-align: center;">التخصص</th>
      <th class="arabic border" scope="col" style="text-align: center;">تاريخ اخر عودة</th>
      <th class="arabic border" scope="col" style="text-align:center;">العنوان</th>
      <th class="arabic border" scope="col" style="text-align:center;">الكتيبة المنقول إليها</th>
      <th class="arabic border" scope="col"></th>
      
      
      
      
    </tr>
  </thead>
  <tbody>
    {% for soldier in soldier_list_filtered %}
    
      <tr id={{soldier.id}}>
          <td class="arabic border">
              {{forloop.counter}} 
          </td>
        <td style="text-align: center; min-width: 250px;"  class="arabic border" >
          <a href="{% url 'armydbapp:soldier_information' %}?soldier_id={{soldier.soldier_id}}">{{soldier.name}}</a>
          {% if soldier.is_at_vacation %}
            <br><span class="badge badge-secondary">تاريخ العودة: {{soldier.return_date|date:"Y/n/j"}}</span>
          {% endif %}
          {% if soldier.is_at_vacation_sick %}
            <br><span class="badge badge-secondary">!!!اجازة مرضية!!!</span>
          {% endif %}
          {% if soldier.is_awaiting_trial %}
            <br><span class="badge badge-secondary">!!!منتظر مكتب!!!</span>
          {% endif %}
          {% if soldier.is_absent %}
            <br><span class="badge badge-secondary">!!!غيــــاب!!!</span>
          {% endif %}
          {% if soldier.is_out %}
            <br><span class="badge badge-secondary">!!!{{soldier.outing_type}}!!!</span>
          {% endif %}
          {% if soldier.is_in_mission %}
            <br><span class="badge badge-secondary">!!!{{soldier.mission_type}}!!!</span>
          {% endif %}
          {% if soldier.is_rewarded and soldier.reward_days > 0 %} 
            <br><span class="badge badge-secondary">عدد أيام المنحة: {{soldier.reward_days}} </span>
          {% endif %}
          {% if soldier.is_at_punishment%} 
              <!-- {% for p in soldiers_punishments %}
                {% if p.soldier == soldier %}
                  <br><span class="badge badge-secondary">نوع العقوبة: {{p.punishment}}</span>
                  <br><span class="badge badge-secondary">تاريخ بدأ العقوبة: {{p.start_date|date:"Y/n/j"}} </span>
                  <br><span class="badge badge-secondary">تاريخ نهاية العقوبة: {{p.end_date|date:"Y/n/j"}}</span>
                {% endif %}
              {% endfor %} -->
              <br><span class="badge badge-secondary">نوع العقوبة: {{soldier.current_punishment.punishment}}</span>
              <br><span class="badge badge-secondary">تاريخ بدأ العقوبة: {{soldier.current_punishment.start_date|date:"Y/n/j"}} </span>
              <br><span class="badge badge-secondary">تاريخ نهاية العقوبة: {{soldier.current_punishment.end_date|date:"Y/n/j"}}</span>
            {% endif %}
        </td>
        <td  class="arabic border">{{soldier.soldier_id}}</td>
        <td  class="arabic border" >{{soldier.current_army_unit}}</td>
        {% if soldier.current_army_unit == "قيادة الكتيبة" %}
          <td class="arabic border" >  -  </td>
        {% endif %}
        {% if soldier.current_army_unit != "قيادة الكتيبة" %}
          <td class="arabic border" >{{soldier.point}}</td>
        {% endif %}
        <td  class="arabic border">{{soldier.service_start_date|date:"Y/n/j"}}</td>
        <td  class="arabic border">{{soldier.service_end_date|date:"Y/n/j"}}</td>
        <td>{{soldier.speciality}}</td>
        <td class="arabic border">{{soldier.return_date|date:"Y/n/j"}}</td>
        <td  class="arabic border" style="text-align: center;">{{soldier.adress}}</td>
		<td class="arabic border" style="text-align: center;">{{soldier.zucchini}}</td>

        <td>
          <li class="dropdown">
              <a href="javascript:void(0)" class="dropbtn"><img src="{% static 'armydbapp/images/s1.png' %}" alt="dropdownicon" height="42" width="42"></a>
              <div class="dropdown-content">
                <a  href="{% url 'armydbapp:present' %}?soldier_id={{soldier.soldier_id}}">حضر من الغياب</a>
                <a  href="{% url 'armydbapp:add_vacation' %}?soldier_id={{soldier.soldier_id}}">إجازة</a>
                {% if soldier.current_army_unit == "قيادة الكتيبة" %}
                <a  href="{% url 'armydbapp:add_work_assigned' %}?soldier_id={{soldier.soldier_id}}">إضافة العمل المكلف به</a>
                <a  href="{% url 'armydbapp:add_job' %}?soldier_id={{soldier.soldier_id}}">إضافة الحرفة</a>
                {% endif %}
                <a  href="{% url 'armydbapp:add_zucchini' %}?soldier_id={{soldier.soldier_id}}">الكتيبة المنقول اليها</a>
                <a  href="{% url 'armydbapp:add_img' %}?soldier_id={{soldier.soldier_id}}">إضافة صورة</a>
                <a  href="{% url 'armydbapp:add_promotion' %}?soldier_id={{soldier.soldier_id}}">إضافة ترقي</a>
                <a  href="{% url 'armydbapp:add_reward' %}?soldier_id={{soldier.soldier_id}}">إضافة منحة</a>
                <a  href="{% url 'armydbapp:reward_consumed' %}?soldier_id={{soldier.soldier_id}}">تم منحه</a>
                <a  href="{% url 'armydbapp:mawkaf_a5eir_sarfaya' %}?soldier_id={{soldier.soldier_id}}">موقف اخر صرفية</a>
                <a  href="{% url 'armydbapp:add_vacation_sick' %}?soldier_id={{soldier.soldier_id}}">إجازة مرضية</a>
                <a  href="{% url 'armydbapp:mission' %}?soldier_id={{soldier.soldier_id}}">إضافة مأمورية</a>
                <a  href="{% url 'armydbapp:no_mission' %}?soldier_id={{soldier.soldier_id}}">إزالة مأمورية</a>
                <a  href="{% url 'armydbapp:outing' %}?soldier_id={{soldier.soldier_id}}">إضافة إلي خوارج ثابتة</a>
                <a  href="{% url 'armydbapp:no_outing' %}?soldier_id={{soldier.soldier_id}}">ازالة من خوارج ثابتة</a>
                <a  href="{% url 'armydbapp:change_army_unit' %}?soldier_id={{soldier.soldier_id}}">تغيير التمركز</a>
                <a  href="{% url 'armydbapp:add_punishment' %}?soldier_id={{soldier.soldier_id}}">إضافة عقوبة</a>
                <a  href="{% url 'armydbapp:awaiting_trial' %}?soldier_id={{soldier.soldier_id}}">منتظر مكتب</a>
                <a  href="{% url 'armydbapp:trial_done' %}?soldier_id={{soldier.soldier_id}}">تم عرضه</a>
                <a  href="{% url 'armydbapp:absent' %}?soldier_id={{soldier.soldier_id}}">غيــــاب</a>
                <a  href="{% url 'armydbapp:delete_soldier' %}?soldier_id={{soldier.soldier_id}}">مسح بيانات الجندي</a>
            </div>
          </li>
      </td>
                  
      </tr>
      {% if soldier.is_rewarded and soldier.is_at_vacation == False and soldier.reward_days > 0 %}
        <script>document.getElementById("{{soldier.id}}").style.backgroundColor="green";</script>
      {% endif %}
      {% if soldier.is_at_vacation %}
        <script>document.getElementById("{{soldier.id}}").style.backgroundColor="yellow";</script>
        {% if soldier.is_rewarded and soldier.is_at_vacation and soldier.reward_days > 0 %}
        <script>document.getElementsByClassName("reward-days")[0].style.backgroundColor="green";</script>
        {% endif %}
      {% endif %}
      {% if soldier.is_at_punishment %}
      <script>document.getElementById("{{soldier.id}}").style.backgroundColor="red";</script>
      <script>document.getElementById("{{soldier.id}}").style.color="white";</script>
      {% endif %}
  {% endfor %}
  <td style="height: 800px"></td>
  </tbody>
  
</table>   
</div>
{% endblock content %}